### ISSUE TITLE
[BUG] Auto Import doesn't work if path contains spaces

### ISSUE THREAD

**Issue by TheHacky** [jeffcampbellmakesgames/Genesis#27]
**Describe the bug**
If the unity project path contains spaces the dotnet command will fail.

**Unity Version:**
Unity 2019.4.12f1

**To Reproduce**
1. Create a new Unity project with spaces in the folder or project name
2. Do install instructions for Genesis
3. see an Unexpected error in the console

**Expected behavior**
Auto Import should work properly

**Additional context**
I will create a PR for this issue because it is enough to add quotes around the argument's path.

**Comment by jeffcampbellmakesgames** [comment]
This fix is included in v2.4.5 and should be available on openupm shortly
