### ISSUE TITLE
[FEATURE REQUEST] Open a discussion forum for Genesis

### ISSUE THREAD

**Issue by JesseTG** [jeffcampbellmakesgames/Genesis#29]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to ask usage questions without cluttering the ticket system.

**Describe the solution you'd like**
The Discussions tab for this repo ~~(and Entitas Redux, while you're at it)~~ to be opened.

**Describe alternatives you've considered**
Opening issues, or bugging you on Discord.

**Comment by jeffcampbellmakesgames** [comment]
Good idea, I've enabled the discussions feature for this repo and will do the same for Entitas Redux
