### ISSUE TITLE
[FEATURE REQUEST] Support for loading Genesis config from `.properties` files

### ISSUE THREAD

**Issue by JesseTG** [jeffcampbellmakesgames/Genesis#31]
**Is your feature request related to a problem? Please describe.**

I want it to be easy to edit and maintain the configuration outside of the Unity editor, because I manage the process of code generation almost exclusively outside of the editor. JSON works, but its inability to use newlines means it's an enormous pain in the ass to configure properties that need to extend past one line.

**Describe the solution you'd like**

The ability to load Genesis config from `.properties` files, just like legacy Entitas supports.

**Describe alternatives you've considered**

Managing my Genesis config in the editor. However, that means I'd have to implement a custom drawer for each config item I implement. Also, if my code doesn't compile then I can't *use* these custom drawers.

**Comment by jeffcampbellmakesgames** [comment]
This has been accomplished and merged, available in `v2.4.6`
