### ISSUE TITLE
[BUG] `unity_temp_config` file being created with a double file extension `.json.json`

### ISSUE THREAD

**Issue by ryanwiesjahn** [jeffcampbellmakesgames/Genesis#34]
**Describe the bug**
When installing Genesis (and Entitas Redux) into a project for the first time, I experienced an issue where the `unity_temp_config` file was being created with a double file extension `unity_temp_config.json.json`. This caused Genesis to not be able to find any plugins, and thus not generate any code.

**Operating System:**
macOS 12.3.1

**Unity Version:**
Unity 2021.3.0f1

**Genesis Version:**
v2.4.6

**To Reproduce**
Go through the normal installation process as described in the Genesis and Entitas Redux Wikis.

**Expected behavior**
The `unity_temp_config` file is created with the proper extension, i.e. `unity_temp_config.json`

**Screenshots and Files:**
[Auto Import - Output.txt](https://github.com/jeffcampbellmakesgames/Genesis/files/8585160/Auto_Import_-_Output.txt)
[Generate - Output.txt](https://github.com/jeffcampbellmakesgames/Genesis/files/8585159/Generate_-_Output.txt)

<img width="427" alt="Screen_Shot_2022-04-28_at_11 16 46_AM" src="https://user-images.githubusercontent.com/708964/165815326-9d5ff10c-2094-451a-aafb-c2e2a472c09a.png">

**Additional context**
- The `Genesis.CLI` folder is in the root of the project folder.
- .NET 3.1 installed
- Unity project is set to use .NET Framework 4.x
- Clicking "Update Genesis CLI" in Genesis Project Settings says `Genesis CLI is up-to-update.`
- Clicking "Install or Update Plugin" next to Entitas Redux says `[Genesis] Successfully installed plugins for [Entitas Redux].`

**Comment by jeffcampbellmakesgames** [comment]
Hi @ryanwiesjahn. This has been fixed in Genesis `v2.4.7`  and Entitas Redux `2.1.4`.
